package com.github.yournamehere;

import android.content.Context;
import android.graphics.Color;
import android.text.SpannableStringBuilder;
import android.text.style.ForegroundColorSpan;

import com.aliucord.annotations.AliucordPlugin;
import com.aliucord.entities.Plugin;
import com.aliucord.patcher.Hook;
import com.discord.stores.StoreStream;
import com.discord.utilities.textprocessing.node.UserMentionNode;
import com.discord.models.guild.Guild;

import java.util.Map;

@AliucordPlugin
public class MyFirstCommand extends Plugin {

    @Override
        public void start(Context context) {
                try {
                            patcher.patch(UserMentionNode.class.getDeclaredMethod("render", SpannableStringBuilder.class, Object.class), new Hook(callFrame -> {
                                            SpannableStringBuilder builder = (SpannableStringBuilder) callFrame.args[0];
                                                            callFrame.setObjectExtra("startIndex", builder.length());
                                                                        }) {
                                                                                        @Override
                                                                                                        public void after(de.robv.android.xposed.XC_MethodHook.MethodHookParam param) {
                                                                                                                            SpannableStringBuilder builder = (SpannableStringBuilder) param.args[0];
                                                                                                                                                int start = (int) getObjectExtra("startIndex");
                                                                                                                                                                    int end = builder.length();
                                                                                                                                                                                        
                                                                                                                                                                                                            UserMentionNode node = (UserMentionNode) param.thisObject;
                                                                                                                                                                                                                                long userId = node.getUserId();

                                                                                                                                                                                                                                                    if (userId == StoreStream.getUsers().getMe().getId()) return;

                                                                                                                                                                                                                                                                        boolean isMutual = false;
                                                                                                                                                                                                                                                                                            Map<Long, Guild> myGuilds = StoreStream.getGuilds().getGuilds();
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    for (Guild g : myGuilds.values()) {
                                                                                                                                                                                                                                                                                                                                                            if (StoreStream.getGuilds().getMember(g.getId(), userId) != null) {
                                                                                                                                                                                                                                                                                                                                                                                        isMutual = true;
                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int color = isMutual ? Color.GREEN : Color.RED;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        builder.setSpan(new ForegroundColorSpan(color), start, end, 33);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (Exception e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        e.printStackTrace();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public void stop(Context context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    patcher.unpatchAll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        